[package]
name = "antaresia"
version = "0.1.0"
authors = ["Robin Voetter"]

[dependencies]
lalrpop-util = "0.15.1"
lazy_static = "1.0"
phf = "0.7.21"
phf_builder = "0.7.21"

[build-dependencies]
lalrpop = "0.15.1"
